name: axbm
favicon: null
layout_spectrum: 0.9171555684879422
typography_spectrum: 0.9826432431582361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6465760464780033
  lightness: 0.4709109414834529
  saturation: 0.5737822318915278
  rhythmicContrast: 0.9658448579721153
purpose: []
