name: axbm
favicon: null
layout_spectrum: 0.48978
typography_spectrum: 0.75
title: 'Emerging Technologies in Law Libraries & Legal Education'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#eff4f7'
    - '#aba58f'
    - '#3f3826'
    - '#00558c'
  brandStrength: 0.6465760464780033
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.9658448579721153
purpose: []
